### PR TITLE
Remove transitive dependencies included by aodn/netcdf-iterator#6

### PR DESCRIPTION
**Pull request by jonescc**
Align iUpdateSpatialExtent dependency versions with other component versions

### CODE REVIEW

**Comment by anguss00** [comment]
Do we need to rebuild talend-components now @jonescc?

**Comment by jonescc** [comment]
Yes - the edge build in jenkins.  I'll kick it off.

**Comment by anguss00** [comment]
Just wondering whether that will trigger a talend rebuild on the harvesters??

**Comment by jonescc** [comment]
No.  Only changes in the harvesters rep will do that

**Pull request merged**
