### PR TITLE
Handle array char

### PR DESCRIPTION
**Pull request by jonescc**
Allow netcdf char type variables to be returned as byte/chars or as strings according to requested talend field type

Prior to this all char type variables were initially converted to a string type by converting the last dimension of the variable into strings.   This strings returned were then used to return char/bytes, by taking the first character of each string, making it difficult to access the character variable as chars in talend.

Now the last dimension is converted to a string only when the requested talend field type is a string.  In all other cases, the netcdf char value is converted directly to the required data type.

### CODE REVIEW

**Comment by danfruehauf** [comment]
GL!

**Comment by julian1** [comment]
Craig says he's using maven!

**Comment by lbesnard** [comment]
hum, was actually testing this as Craig asked me too. prob would have been better to do this before merging it. 

I actually have some issues @craig if you have some time

**Comment by craig** [comment]
No, I don't have time! GO AWAY!

**Comment by danfruehauf** [comment]
LOL.

**Pull request merged**
